replicas: 1
postrixImage:
  repository: yuvadius/backoffice
  tag: latest
containerPort: 3000
ingressPort: 3000
servicePort: 3000
serviceTargetPort: 3000
resources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 5m
    memory: 150Mi
