apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backoffice
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: dev-backoffice.postrix.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backoffice
                port:
                  number: 3000
