---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: next-auth
  namespace: secrets
spec:
  encryptedData:
    next-auth-secret: AgBmkj3nzZjsRZyYnXEtT3fnrQAEerm8w9JSVPaSCc4xazbeL5m2XkfWnp/hpLflDjlvnF5YCH2td7vyMqX1ssNaqn1KhXspbbB4M8YIzzXmR+aZiaS3ukBt+/ls5jsWFhMCErgX+fneOpnqpdgO8GOMVvIRtc91eq0msmKZTcOwylwqewcbAAtQy3NWoXMAP1bKpPRpDsSGXFHcJzAKK9J8c3UNEKIAotTIAtFRaJqt5xpRX1lGdVCJ4q4QGJatZPVuYG7RO84NWgtfzGCbMDKA644ReDx8BDOGx49LsfGwa5Bn/iwc3RgiR3NljgfSUVLgtspyZHOpUDM23aMOSWpzXn4DoLpqx4YUICseOPZTsEqvlrqcaqHZCcpGGXImCx+VuDckvjPwiJanWnVvqEcHYNEA/DouFEioB1BHLJn5obQATmURZAiHAeEw0k6huEw/M/mzDJVkGoTGVIPAGq7yxTvUE01tJDYRw46aIu/NYDYk/3aOwuBPpK7Y7NzI7faw1J5MlZT8AHxBOBVS4wPdVNQ4FlIzYRu/iC8Tepn6VgJpYgLDFVolPK4XqpW4ipzcAKvipGPEtlwQv+8Iq87bEP7kXIh6PiQhJdm5ZMEuI/VoXAUzgo/YIjU8mNcwWOhTt6fJNBNEtau96CZf7tJ1nHNMn9Fo4xSuWaFLJlHTIpXDnueAqByuzAIzfnOOEtClUoe1/LbGDP9IRA65Lff6V59zQ6os65yGRrvShxS30rVUcTGw35+aECRSDg==
  template:
    metadata:
      creationTimestamp: null
      name: next-auth
      namespace: secrets
