---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: polymarket-auth
  namespace: secrets
spec:
  encryptedData:
    polymarket-address: AgAWDeamEgwKyJ/29xq+Y62O67Sg+s3Z2C+D4nJwO/mGwnYu/qYjjHpDzr+EoK1YO5pcIT1ubmtgyKJ3pQ9Ji+eTaLQMQSWimXfH1I17EYjM5lpDhs6qoNhjejE4HhOT5oUy3KxdX/iZouV4d9mhLn359+4581UU4ydAmLl/Mt748NIGE6glqifGdUum9K936YkLMKHVVNr03OTE7I6DEF8GBgqrFipIVfhs8aYL/4T4x7Dj+gQOTErJMnzdTnUFZQsA/L35B5kKKylQpUhbsccX9YnOtvrUuDKfTXe5/UP3w19G8Z6RZ5mgbiXtSkeH0smPas5TBPvDjd9HpAzV4efselfJ9w/rXPEcj31swJ6l1uBLOOw/WneRoNaZXoHH//JioZOqk9yAMFLlLnbRwdlu/8VZniVYRLF3gUuWCmU3kFhxfgnVLfovMxuY1zocH2Svq+rIAJHdQHfbOrN8OTexPObrZVO5n7EcWwwsQ8RpuxZKs2vmFDQUCUZf4aV5j6rYnm6uRq6snLPmYwQ4ZOEJ80cTYWpzOUCcbCcNjY8qU/PvH7KQnG1z2MUYAvg+pZ1OD9Xp6qqtBQ44kak90t9QtEkWJSr74+iHdXifJo0HHGINuWArnQaBJ9uEjD/MllZ291kk/6FDTpY8A9fNcrZoaHVgCOYfcg2O7lYXzpGA1G8D1ZCHjheWmKEL10Xs4xKIhzIlnHQtZ+2Ex65ofm2Syiy8lkC4lP2wW+Cx5pUnzlGs2Ta+LawVJ0Q=
    polymarket-api-key: AgAeHiTk/n9Qzk635g6Za2mYYJl+gt3qRK5v3PWpC/cO/zJ4Zx7za6LQygouPK5EMVZpDesB0aKmyTU3HXTFfaIOp4pQ5nT5qoitoXtEpMWY7IzkFAFTBeoh4yKQw1uO1Nm+kmnIgHNC3enFGECdLfUvdC3ifZeWwxtwTGTfa+BkfcTA3SxfBRgGMzusmAPv6kVDsHvUSTR45dljuxF9psmpnki6F9ZGfZH236rwQ1rKbzxaMoNjByxLwQftN5artZvIxoIEunlNP3vG6ECk7nLT+Cxkks60c0ESylbgD6MKQGjZR/YdrPliS/440w7HNbn+QXtWKqmDnxBMkR34A2nSavRJJseva46XOIyikxYcP5ela51bdsKMmujPSiiGc44lGYOAV+tr5Z4nQndFAH993Zp4DDeAnG3be4tdgymeVjo9h6rpLHl0gK29KR+LdNjQT4sSvDsn86ifIQ2CiAUQUD5kETbQqJfR7f+JPwQ7kkV/Q9UUBNHxJC3oiRM5zsuGWJtqpnrEOKzrkRbdU5G2V8fzHZ7HT1oQgVrD/bUpwbiaVzzupZPnxp3DdqdJVGUDuBYIfbGlNf5W2dYWh9k88JLOWnUuy5G4rv/ijLtvUavqxaKVydfGscQI2yA8OnGzo5yAhcuoOlyFcAGoDhryY5wejlniTLCuN268bl51cmTQXED69vRXBvnyewPtEdRI0h1auUqt0pqgUXl+bAouJuwSzvRTEOr5Kb1o5QdwMlMpY2OFds13BAx3cVhfb72AnygoM3yK9EnBdcD0P+196G4=
  template:
    metadata:
      creationTimestamp: null
      name: polymarket-auth
      namespace: secrets
