---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: smtp-auth
  namespace: secrets
spec:
  encryptedData:
    smtp-password: AgB/RRXecTWrZf2xVn32pBtTQ1iXJKJXwAOAsGHLHA5XSb7KCMPG4TNG/h9A/ahwv9zsEexgjnffNm1ZrMAkP74deXD9T/rUAQtbyNsYGDAFsYy8ayBEf2Dd1HHoF11feVGT+HQBAFDTEKv6dmBRvlsOu45mGb9R83EeOFsQdNO1Zv/m11GfP0Ly0cfauzg0jjzTgj0bKCfGfGPpxs4YMP4uAF0IYcn9wu8MRVjh9WccwDc3vumSn2sL6eE3gp8dFW3s8SqPgkiOLKOG5dfo5CxtGgHpGGZUxuuQRpEiNTH3uMEHkZqT5KQRd/NJ04HARyoZUgqG1niOhkzQmz5RRk3NqvMnDZm6y1kCs2dr73yp+REOrku8kCDVJc5h4/c4FvWEkqyOQoGjVD1M4OrPeY5UfV4nr6DsOGg0yp/Z64B/BKECBsox6Yk1GY/KA+pfqLjt40tGROcTz/GFUPDIlfYgtvnN9xaBu/MS0LB5jX0d7LpUGBxC9sQqRE6bylLXxaDZcZ1D9mQ7AvL7059wP6DCyixMG7ztL+3ZLmo371mVJ73tOKm3qmu31TWGqxd8mRQRj8MFCjhxwX3dA0OEd3AK16VStfRxnAZ/BA73Lj7D1bfq1+UjxC+dos/lccIuEi1Nyz+2lSzikFrVWjrEIPsXZ3b0XdMBZUDd+OvRwRET7FGtY8nGU/5PqeIx07KmY14dKBq7MFsREf9VW1BY/8xX
    smtp-user: AgCFeR5XEgBYKACwj3w0ga4NiRWyCh3M/q2cE0rJHCjdAPEHAaQFZVA/XVuhp33b2i3Ot7j6wCFk9wej/Z022TVsTydtErGrrQzA84ghjsqTbS3ArNeaRwy7RFGWhOOz0boin4FCTlaK0xADpZorP2KwojpFtdZJYZ6h/J1XdNRVWmSJX1J05+I8UKdzICUax6nIAMw7ZgYQJLUmlxtwBl4myQkZMWQDe2c0VVQVbJnJUry5eY3KxuD3YvBhzLvOmOhRa+dgrQQhC5uwe6ghX6kzX9oGeHvZu3l4iGeLmoCRQqSMaIvcdzt04Yz7Nyz1l4AZEi33IuY0nUr0Scg8MmgEtNOZMcQH5Jt4v0DE5bkQaTLDlprUHcdSjc2i9t6G0YA4ohfUHTnwWwT2Yp7jA1Ykm36ZdEaRPrbcdaJpuxv5nGdIEhHN09UGTRcfiGHqcvVbkpI7Fm7lucKFPALCX/aOkMRcsMYAMx5/A3Kr2Kc6xQFaqtc+aoudH2GyUx16a8TW/+xvrIedlj+WABFto6KabHZ9wtMVjt141kW0BStAlG6ghn2CPtYjTU/MHHvLmt6o4RdfDp+BSLaWIdn3ns56lMheuIxr6lePsWDT+KPAQEe5JHFTiwklkqru4jWUiTVDnci0JMmPyNcTpLpEp8LIPW6wtPmOhP2uA6JvFJP1ULS4wZoVpSU+yCNBec5ELC+xZc+AuM7gjNPF6aHivybfobK1VuHIftXR
  template:
    metadata:
      creationTimestamp: null
      name: smtp-auth
      namespace: secrets
