apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-n8n
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "false"
  # Tags for the EBS volume
  tagSpecification_1: "Name=n8n-persistent-storage"
  tagSpecification_2: "Application=n8n"
  tagSpecification_3: "Component=database"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
reclaimPolicy: Delete