apiVersion: v2
name: n8n
description: Custom n8n deployment
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: n8n
    version: "1.1.0"
    repository: "oci://8gears.container-registry.com/library"