---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-auth
  namespace: monitoring
spec:
  encryptedData:
    admin-user: AgAjdzD7lkh8nT87rXGhP4ZROzdFWmGg019DFxI80cIR87Wr5yNXVCJELWxImeq9SINCfgDxHjjOfTCiJ1WTWxCAKZAbzsuG8ifs4zIdb543nK2uijDRxSM3ksiHA5eNARBo8CzJs8/G9vNGi5yWsIOe5PXqvzROi1cZLtYpqM5+F9h6XVhbp4sMEVEj2aQPkNhU/AzRf3OEFBw/RU1L3zv+cVqRUUhnrk2zBfWa5p9JQwEmOWhtC27aLlOfPtCrYUeD9S/vGmGsktC5uT5UtiCS1BZXfzBca28dLiXdPRUMKNY8qnhofYSdIR2udVw1GzhuygREdXhzYmMuCXhoyZiStMIv4qAgem9Pl7xIBaXPIkt6pFnYR1qCHjMN9Jx1qjEMfsSQfUL/kVYl87QU+hcW8wX4pT7pKL0YqBA/JCNZcN5fQo9Cbs6z860NqB2N1xGVlZ6CBvumjOXDUNNZBnwa6Sgj9VtDQU0+z7h3rq9rO4mqOCBTRdKG+ZqqCG+NgdbEhIjpBle6qcwcRdk5neH+o7crbd12HOmczXf+71AQppW8wFIglxZsNGwCMLyqxdRZWUYaDOPdgxMQVAw4NuXqgdpB6EnOlR+GLnnoHsI3ZW/S0w5n5TO4ET0wLNef/7nswZhWvy1PoIGu+BWKjukG2QcbN9nNuaGs9MjB+TYpXWCnxnTJ1WcJY/eCp17POgxg4hE3zw==
    grafana-password: AgC0hTSCdJ/1YC+3ApHultJpCVaPNbV7FRIpuBbV+Q2syPVJMve8b6WnrZ7HsZI4tEsLepETbiLw4EkclRglejnp3ow7eIrrQJYO9d4VEVfNH2L8slbuxDLu3oc1DEsGiH6hbsuhy7aw3yAPSRzdSc4gGlbjCfoFYoAgsoVnu2sQGbGOB3Na1M5AMN+XCjQBrc/ghLjtwIKfNO9TRpsOh9ETOFU6E0c2BmcHXKR4phha7+ah6eTT2p0Yn5SwPVTD7DwyqYIVVfnnDyJtR8qicIZjAZL5+TLbK8KV8y14O7CeSivpVmnjKDrXT3UQvDkgsebEG16P+bgwShp5S17C0AhAaH+pHWbi3ti4pEbssSDN6QlAhD1OPxNH6Bo0mKsdzAR/DfUp6D0JtnExc1U3mytMwj92+YsX3hipbJvNu+oVY6NG8ZcHLwqyxx6UwZIidoFBbVRgM5m9A32hxT2+oBi/tXiAAh3o9ufi/b24ihN0cdEIRA97vwhiOoF3QXHeeZE0GobgqfypcFnm4pCy/+dxZSW9t2BKBsNle0BI4FsuvuDCkIjSXvk1s7ZIeubbgVDIGofkiF//PSENZLbO1SEJFhREybmGNfrGy+Nz/PSC2e4m7jk7W9ZfWmGy1rwXsQXeHKpeMtCGUjQrW0K+1N2p+GA/vFp2xTm51LU4/WMALATjWg3lXK6zNEknu6aCiMAJ3BVXMcyLM/c=
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-auth
      namespace: monitoring
