apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-prometheus
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "false"
  # Tags for the EBS volume
  tagSpecification_1: "Name=prometheus-persistent-storage"
  tagSpecification_2: "Application=prometheus"
  tagSpecification_3: "Component=monitoring"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain

